### ISSUE TITLE
Duplicate Work

### ISSUE THREAD

**Issue by a1300** [AschPlatform/asch#104]
Dear Asch-Team,

I would like to see the project management on github. On which topic each one of us is working on. I really dislike doing duplicate work.

I revised the work for Dapp-Documentation on [a1300/asch](https://github.com/a1300/asch/blob/master/docs/dapp_docs/1_hello_en.md)

I saw that you also published a new document (in chinese).

I would really like to see the work coordinated. Because it is really frustrating to work for nothing. The documentation was until 4 days ago not really helpful and I spend 15 hours to get one single dapp on my localnet running. I had to read the source code of asch and asch-cli and asch-js to get it running.

Please, can we use the **Assignee** on github to track the work of each member.

@ByCnck @kimziv @yanyiwu @sqfasd @langson-leung 

Thanks in Advance!
Kind regards
a1300

**Comment by yanyiwu** [comment]
thank you for your advise about project management.

but i am wondering about what you are frustrating on, because i saw the [compare](https://github.com/AschPlatform/asch/compare/master...a1300:master) and i find out what you did is not duplicated work. i think you do a great job and can be merged anytime. 
and the updated Chinese document which you mentioned is some little changes, i don't think they are duplicated with your work.

so maybe you can just post the pull request more frequently , just like me , even though i did a little change, i would pull request immediately, to void the duplicated work by someone else.

sure, using the **Assignee** to track the work of each member is a good idea, @sqfasd @ByCnck @liangpeili @a1300 @eagleHovering @lbgod2222 we should try it to work coordinated. 

thank you for your work again.

**Comment by a1300** [comment]
Dear @yanyiwu 

I didn't wanted to sound so frustrated. I think it is kind of duplicate work. Normally I would make a translation of the chinese documentation into english. And then from english to german.

However, if I push now my changes, the overall structure of the dapp documentation in chinese and english is different.

Thanks for your suggestion, to make a pull request more frequently! :-)
Kind regards
a1300

**Comment by a1300** [comment]
Dear @yanyiwu 

What are your plans for the documentation?
Asch has several dapp documents that I find should be improved. [Link](https://github.com/AschPlatform/asch-docs-site/tree/master/source/dapp). Can we also merge them into the [asch/docs](https://github.com/AschPlatform/asch/tree/master/docs) main repository?

My suggestion would be that you update the chinese version and I do and english and german translation. 

I would be happy to hear your thoughts on this :-)

Kind regards
a1300

**Comment by yanyiwu** [comment]
> Dear @yanyiwu
> 
> What are your plans for the documentation?
> Asch has several dapp documents that I find should be improved. Link. Can we also merge them into the asch/docs main repository?
> 
> My suggestion would be that you update the chinese version and I do and english and german translation.
> 
> I would be happy to hear your thoughts on this :-)
> 
> Kind regards
> a1300

good idea, but i thought we already did it on [pr](https://github.com/AschPlatform/asch-docs/pull/17/commits/4c20bf45ef703b646123170ded2ec623a36407a2) , 
and now i am wondering why it is missing ? 
and i think it is better to open a new issue for that.
