### ISSUE TITLE
Question about the (user)name in registerDelegate

### ISSUE THREAD

**Issue by bassjobsen** [AschPlatform/asch#246]
The code tells me that a account that will become Delgate should already have a (user)name, see https://github.com/AschPlatform/asch/blob/master/src/contract/basic.js#L330

The above means that one should set a `name` before registering as Delegate.

On the other hand `asch-cli` enables me to set a `--username`  when doing `registerdelegate`. Same for other UI (like asch-frontend-2).
So what to do when i try to register as a Delegate with a (username)????

First when the account does not have a name, should it be set to the name set by the UI / CLI? And what if a username is set  by the UI / CLI which do not match the username set before for the `Account`?

**Comment by a1300** [comment]
@bassjobsen the problem is, that the `asch-cli` package is outdated. The current `asch-cli` package uses the _old_ (ASCH 1.3.6) transaction API and the old transaction API needs the __username__ for the delegate registration. 

The outdated `asch-cli` package uses the outdated `asch-js` package. Both need to be updated.

**Comment by bassjobsen** [comment]
@a1300 yes thanks for the explantion. That makes sense i will close the issue now
